
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: gana2111
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
volumes:
  db_data: